name: uc-python-intermediate
channels:
    - defaults
    - conda-forge
dependencies:
    - python>=3.9
    - pip>=20.3
    - nbconvert>=6.1
    - numpy=1.19
    - pandas=1.2
    - seaborn=0.11
    - ipykernel>=6.4
    - jinja2=2.11
    - jedi=0.17.2
    - scikit-learn>=0.24
    - plotnine>=0.7
