name: uc-python
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.9.7
    - pip>=21.2
    - numpy=1.21
    - pandas=1.3
    - seaborn=0.11
    - ipykernel=6.4
    - ipython_genutils=0.2
    - jinja2=3.0
    - jedi=0.18
    - scikit-learn=1.0
    - plotnine=0.8
